### ISSUE TITLE
Pinned tab with normal or shrink size

### ISSUE THREAD

**Issue by AkazaRenn** [EmrecanKaracayir/winscode-11#6]
![Screenshot 2023-06-09 093315](https://github.com/EmrecanKaracayir/winscode-11/assets/8340896/7013eb19-bcd2-42ab-ad21-7d910c74309b)
As you can see in the screenshot, when scrolling through the tabs with a pinned tab being in `normal` or `shrink` size, you can see the tabs through its background. I think you set the background to transparent but it would be better just to put it the same color as the title bar instead.

**Comment by EmrecanKaracayir** [comment]
This version is no longer maintained. 

Please transition to [Codemos Modern](https://github.com/Codemos-Inc/codemos-modern)

**Comment by EmrecanKaracayir** [comment]
Check if this issue is persists in Codemos Modern.
